### ISSUE TITLE
Initial commit

### ISSUE THREAD

**Issue by loxygenK** [approvers/assignment_manager#1]
I'll do later
cuz i didn't install android studio in macbook air lol

**Comment by Colk-tech** [comment]
lol
JUST DO IT.

**Comment by loxygenK** [comment]
oh no no i don't have tool 
should i install it now

**Comment by Colk-tech** [comment]
what version should I install and which version are you installing

**Comment by loxygenK** [comment]
i installed 3.5.3 for mac

**Comment by Colk-tech** [comment]
3.5.3 for mac
3.5.3 for windows

**Comment by loxygenK** [comment]
is there 3.5.3 for win?

**Comment by loxygenK** [comment]
btw what android version should i set minimum bro
i want to set it as Android 6.0

*edit - bad English

**Comment by Colk-tech** [comment]
it's ok to set minimum andro ver. 6.0

**Comment by loxygenK** [comment]
thank you sir!
can i set package name as `com.brokenmanager.assign_man`?
(package name is the id of app)

**Comment by Colk-tech** [comment]
no problem

**Comment by loxygenK** [comment]
thx sir, i can initial commit now

**Comment by Colk-tech** [comment]
♡
Then i'm cloning to my local

**Comment by loxygenK** [comment]
ok, i could push finally! i close this.
